# ============================================================
# Script: 03_annual_mean_models.R
#
# Purpose:
#   Derive annual literature-based and expert-based Ebola virus
#   disease (EVD) suitability surfaces by averaging the
#   corresponding dry- and wet-season WLC-MCDA outputs.
#
# Inputs:
#   Outputs generated by:
#     - 01_wlc_literature.R
#     - 02_wlc_experts.R
#
# Outputs:
#   - Annual mean literature-based EVD suitability raster
#   - Annual mean expert-based EVD suitability raster
#
# Notes:
#   - Dry- and wet-season models are given equal contribution
#     when deriving each annual model.
#   - The resulting index is a relative, unitless suitability
#     measure and should not be interpreted as a probability of
#     EVD occurrence.
# ============================================================


# ------------------------------------------------------------
# 1. Load packages
# ------------------------------------------------------------

library(terra)
library(here)


# ------------------------------------------------------------
# 2. Define directories
# ------------------------------------------------------------

literature_dir <- here(
  "outputs",
  "wlc_literature"
)

expert_dir <- here(
  "outputs",
  "wlc_experts"
)

output_dir <- here(
  "outputs",
  "annual_models"
)

if (!dir.exists(output_dir)) {
  dir.create(
    output_dir,
    recursive = TRUE
  )
}


# ============================================================
# LITERATURE-BASED ANNUAL MODEL
# ============================================================


# ------------------------------------------------------------
# 3. Load seasonal literature-based models
# ------------------------------------------------------------

literature_dry <- rast(
  here(
    literature_dir,
    "risk_index_EVD_literature_dry.tif"
  )
)

literature_wet <- rast(
  here(
    literature_dir,
    "risk_index_EVD_literature_wet.tif"
  )
)


# ------------------------------------------------------------
# 4. Verify geometry
# ------------------------------------------------------------

if (!compareGeom(
  literature_dry,
  literature_wet,
  stopOnError = FALSE
)) {
  stop(
    paste(
      "Dry- and wet-season literature-based rasters",
      "do not have identical geometry."
    )
  )
}


# ------------------------------------------------------------
# 5. Calculate annual literature-based suitability
# ------------------------------------------------------------

annual_literature <- (
  literature_dry +
    literature_wet
) / 2

names(annual_literature) <-
  "annual_literature"


# ------------------------------------------------------------
# 6. Export annual literature-based model
# ------------------------------------------------------------

writeRaster(
  annual_literature,
  here(
    output_dir,
    "annual_EVD_literature_mean.tif"
  ),
  overwrite = TRUE
)

message(
  "Annual literature-based EVD suitability map exported."
)


# ============================================================
# EXPERT-BASED ANNUAL MODEL
# ============================================================


# ------------------------------------------------------------
# 7. Load seasonal expert-based models
# ------------------------------------------------------------

expert_dry <- rast(
  here(
    expert_dir,
    "risk_index_EVD_expert_dry.tif"
  )
)

expert_wet <- rast(
  here(
    expert_dir,
    "risk_index_EVD_expert_wet.tif"
  )
)


# ------------------------------------------------------------
# 8. Verify geometry
# ------------------------------------------------------------

if (!compareGeom(
  expert_dry,
  expert_wet,
  stopOnError = FALSE
)) {
  stop(
    paste(
      "Dry- and wet-season expert-based rasters",
      "do not have identical geometry."
    )
  )
}


# ------------------------------------------------------------
# 9. Calculate annual expert-based suitability
# ------------------------------------------------------------

annual_expert <- (
  expert_dry +
    expert_wet
) / 2

names(annual_expert) <-
  "annual_expert"


# ------------------------------------------------------------
# 10. Export annual expert-based model
# ------------------------------------------------------------

writeRaster(
  annual_expert,
  here(
    output_dir,
    "annual_EVD_expert_mean.tif"
  ),
  overwrite = TRUE
)

message(
  "Annual expert-based EVD suitability map exported."
)


# ------------------------------------------------------------
# 11. Verify compatibility between annual models
# ------------------------------------------------------------

if (!compareGeom(
  annual_literature,
  annual_expert,
  stopOnError = FALSE
)) {
  stop(
    paste(
      "Annual literature- and expert-based models",
      "do not have identical geometry."
    )
  )
}


# ------------------------------------------------------------
# 12. Completion message
# ------------------------------------------------------------

message(
  "Annual literature- and expert-based EVD models ",
  "generated successfully."
)