# ============================================================
# Script: 04_combined_annual_model.R
#
# Purpose:
#   Generate the final annual Ebola virus disease (EVD)
#   suitability surface by combining the annual literature-based
#   and expert-based WLC-MCDA models with equal contributions.
#
#   Final annual suitability =
#       0.5 * Annual literature-based model +
#       0.5 * Annual expert-based model
#
#   The script also generates a difference raster describing
#   spatial disagreement between the two annual sub-models.
#
# Inputs:
#   Outputs generated by:
#     - 03_annual_mean_models.R
#
# Outputs:
#   - Final annual combined EVD suitability raster
#   - Annual literature-minus-expert difference raster
#
# Notes:
#   - Positive difference values indicate areas where the
#     literature-based model assigns greater suitability.
#   - Negative values indicate areas where the expert-based
#     model assigns greater suitability.
#   - The final index is relative and unitless.
# ============================================================


# ------------------------------------------------------------
# 1. Load packages
# ------------------------------------------------------------

library(terra)
library(here)


# ------------------------------------------------------------
# 2. Define directories
# ------------------------------------------------------------

annual_dir <- here(
  "outputs",
  "annual_models"
)

output_dir <- here(
  "outputs",
  "combined_model"
)

if (!dir.exists(output_dir)) {
  dir.create(
    output_dir,
    recursive = TRUE
  )
}


# ------------------------------------------------------------
# 3. Load annual literature- and expert-based models
# ------------------------------------------------------------

annual_literature <- rast(
  here(
    annual_dir,
    "annual_EVD_literature_mean.tif"
  )
)

annual_expert <- rast(
  here(
    annual_dir,
    "annual_EVD_expert_mean.tif"
  )
)


# ------------------------------------------------------------
# 4. Verify raster geometry
# ------------------------------------------------------------

if (!compareGeom(
  annual_literature,
  annual_expert,
  stopOnError = FALSE
)) {
  stop(
    paste(
      "Annual literature- and expert-based models",
      "do not have identical geometry."
    )
  )
}


# ------------------------------------------------------------
# 5. Calculate annual difference between sub-models
# ------------------------------------------------------------

annual_difference <-
  annual_literature -
  annual_expert

names(annual_difference) <-
  "literature_minus_expert"

writeRaster(
  annual_difference,
  here(
    output_dir,
    "annual_EVD_literature_minus_expert.tif"
  ),
  overwrite = TRUE
)


# ------------------------------------------------------------
# 6. Calculate final annual combined EVD suitability
# ------------------------------------------------------------

combined_annual_EVD <-
  0.5 * annual_literature +
  0.5 * annual_expert

names(combined_annual_EVD) <-
  "combined_annual_EVD"


# ------------------------------------------------------------
# 7. Export final annual combined model
# ------------------------------------------------------------

writeRaster(
  combined_annual_EVD,
  here(
    output_dir,
    "combined_annual_EVD_suitability.tif"
  ),
  overwrite = TRUE
)


# ------------------------------------------------------------
# 8. Completion message
# ------------------------------------------------------------

message(
  "Final annual combined EVD suitability model ",
  "generated successfully."
)